homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 113
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml


# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: odin.finstafl.net:8123
  #ssl_certificate: /config/cert/certificate.pem
  #ssl_key: /config/cert/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
conversation:
history:
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor:
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature
  - platform: plex
  - platform: moon
    host: 10.1.1.21
    token: "LjsUZDJJAqZqyLwsnDrR"
    show_all_controls: true
    include_non_clients: false
    use_episode_art: true
    remove_unavailable_clients: false
    client_remove_interval: 10

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyACM0

ios:
  push:
    categories:
    - name: Update 
      identifier: update
      actions:
      - identifier: update_restart
        title: 'Update & Restart'
        activationMode: 'background'
        authenticationRequired: yes
        destructive: yes
        behavior: 'default'

camera weather:
  - platform: generic
    still_image_url: 'https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=LWX&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=0.5&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25542934&lat=0&lon=0&label=you'
    name: Weather Radar

camera cds:
  - platform: generic
    still_image_url: 'http://www.cleardarksky.com/c/CntrvllVAcsk.gif?c=2152819'
    name: Clear Dark Skies

camera coop:
  - platform: generic
    still_image_url: !secret coopcam_url
    content_type: image/jpeg
    name: Coop Cam
    scan_interval: 5
    icon: mdi:cctv

# Foscam FI8910W
# todo: Update the IP on this webcam
#############
#camera POD:
#  - platform: generic
#    still_image_url: !secret podcam_url
#    content_type: image/jpeg
#    icon: 'mdi:camera'
#    name: 'POD Cam'
#    scan_interval: 5

# left-hand menu sidebar
panel_iframe:
  nodered:
    title: 'Node-Red'
    url: 'http://10.1.1.11:1880/'
    icon: 'mdi:shuffle-variant'
  cloud9:
    title: 'Cloud9 IDE'
    url: 'http://10.1.1.11:8321/ide.html'
    icon: 'mdi:shuffle-variant'

switch:
  - platform: wake_on_lan
    mac_address: "00:27:10:39:65:0c"
    name: "cchristman-dell"
    host: "10.1.3.108"

  - platform: wake_on_lan
    mac_address: "00:24:1D:15:44:FB"
    name: "unraid"
    host: "10.1.1.21"

  - platform: wake_on_lan
    mac_address: "50-C7-BF-CF-7E-66"
    name: "TP-Link Switch"
    host: "10.1.1.5"

  - platform: wake_on_lan
    mac_address: "08:00:27:3D:55:25"
    name: "fedoravm"
    host: "10.1.1.18"

  - platform: wake_on_lan
    mac_address: "c4:9d:ed:76:a2:e5"
    name: "xboxone"
    host: "10.1.1.107"

  - platform: wake_on_lan
    mac_address: "02:0F:B5:66:F0:16"
    name: "powerswitch"
    host: "10.1.3.10"

  - platform: wake_on_lan
    mac_address: "90:2B:34:30:BC:6F"
    name: "cchristman-pc"
    host: "10.1.1.122"

  - platform: wake_on_lan
    mac_address: "02:0F:B5:E2:0A:D2"
    name: "WifiExtender"
    host: "10.1.3.127"

  - platform: wake_on_lan
    mac_address: "0c:47:c9:3b:3a:45"
    name: "Tablet1"

  - platform: wake_on_lan
    mac_address: "0c:47:c9:3b:3a:45"
    name: "Tablet2"

  - platform: digitalloggers
    host: 10.1.3.10
    name: PowerSwitch
    username: !secret powerswitch_username
    password: !secret powerswitch_password

zone:
  - zone: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 250
    icon: mdi:at

#media_player:
#  -  platform: yamaha
#     host: RX-V675
#  -  platform: plex
#  -  platform: roku
#     host: bedroom.finstafl.net
#  -  platform: roku
#     host: basement.finstafl.net


##########
##
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_pwd
# certificate: !secret mqtt_ssl_cert_path
  port: 1883
  client_id: hass_master
  keepalive: 60

mqtt_eventstream:
  subscribe_topic: slaves/#
  publish_topic: master


device_tracker:
  - platform: owntracks

binary_sensor:
  platform: template
  sensors:
    door1:
      device_class: opening
      friendly_name: 'Haustür'
      value_template: >-
        {%- if is_state("sensor.hank_hkzwdws01_doorwindow_sensor_access_control_2", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

